const reasons = [
  "41 reasons why I love my girlfriend :)",
  "1. She likes chromakopia",
  "2. We are the cutest couple ever",
  "3. She loves her stuffed animals",
  "4. We go to microcenter together",
  "5. She is the best gamer ever",
  "6. Yoshi cuddles :)",
  "7. Snaps me hot photos of her",
  "8. boobs :)",
  "9. She took me to my first concert",
  "10. She’s caring and compassionate (she will lie and say otherwise)",
  "11. She showed me how good the lil caesars puffs are :D",
  "12. She is the funniest woman alive",
  "13. We went to ihop together!!!",
  "14. She loves one piece as much as I do",
  "15. Sexy ahhhhhh legs",
  "16. We went to MagFest together",
  "17. She liked my hometown",
  "18. She is camera shy",
  "19. She is shorter than me :P",
  "20. She would die for perona",
  "21. I got cute Europe pics",
  "22. Robin made her shy :>",
  "23. Zoro scar ahhhhhh",
  "24. She waited while I got my controller signed",
  "25. Extremely kissable face",
  "26. Took a photo of me without me knowing >:(",
  "27. She naps on me",
  "28. SO CUTE PLAYING HER DS AWWWW",
  "29. Literally the best overwatch Mei ever",
  "30. Her when brawlhalla",
  "31. She got me a goomba (and fed him froyo)",
  "32. I smell her hair (nobody tell her)",
  "33. Nintendo relationship goals",
  "34. Convinced me not to buy a stupid desk",
  "35. LOOKED ADORABLE WHILE EATING THE BEST PIZZA EVER",
  "36. Likes her Sanrio",
  "37. We gym together",
  "38. She is legit a princess w/ a tiara",
  "39. Let me steal her clothes",
  "40. She got me applebees alcohol ^_^",
  "41. Loves her forehead pics",
  "I love you so much; you are the light of my life and in such little time, we have already made a hundred memories. Thanks for being you baby :)"
];

export default reasons;